fabric_api_version=0.77.0+1.18.2
modmenu_version=3.2.5
packs=outline-renderlevel-1192,width-fixed-1192,options-grid-1192,screen-field,settings-screen-1192,text-components-118
label=1.18.2
range=>=1.18.2 <1.19
java=17
gametest=false
