fabric_api_version=0.77.0+1.19.2
modmenu_version=4.1.2
packs=outline-renderlevel-1192,width-fixed-1192,options-grid-1192,screen-field,settings-screen-1192,text-components
label=1.19.2
range=>=1.19.2 <1.19.3
java=17
gametest=false
