forge_version=1.16.5-36.2.42
packs=outline-event-116,width-fixed-116,options-grid-116,screen-field,settings-screen-1192,text-components-118,forge-client-116
label=1.16.5
java=8
mc_range=[1.16.5,1.17)
forge_range=[36,)
loader_range=[36,)
pack_format=6
