forge_version=1.19.2-43.5.2
mixinextras_version=0.5.5
packs=outline-renderlevel-1192,width-fixed-1192,options-grid-1192,screen-field,settings-screen-1192,text-components,forge-config-screen
label=1.19.2
java=17
mc_range=[1.19.2,1.19.3)
forge_range=[43,)
loader_range=[43,)
pack_format=9
