mixinextras_version=0.5.5
packs=outline-renderlevel-legacy,width-fixed-legacy,options-grid-legacy,screen-field,settings-screen,forge-config-screen
label=1.20.1
java=17
mc_range=[1.20.1,1.20.2)
forge_range=[47,)
loader_range=[47,)
pack_format=15
neoforge_version=1.20.1-47.1.106
